name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104

    steps:
    - uses: actions/checkout@v3
    - run: |
        cd application/server
        npm install
        npm run prisma:generate
        npm run docker:db
        npm run db:init
        npm start
