name: Cypress Encrypted Secrets run
on:
  workflow_dispatch:
    inputs:
      amb:
        description: 'Selecionar algum destes ambientes: dev / hlg'
        required: false
        default: 'hlg'
  pull_request:
    branches: [ "main" ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Write the cypress.env.json file
      run: |
        echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
        
    - name: Run server
      run: |
        cd application/server 
        npm install
        npm run prisma:generate
        npm run docker:db
        npm run db:init
        nohup npm start &
        
    - name: Run admin-ui
      run: |
        cd application/admin-ui 
        npm install
        nohup yarn start &

    - name: Cypress run
      uses: cypress-io/github-action@v4
