name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Server run
      working-directory: ./application/server
      run: |
        npm install
        npm run build
        
    - name: Admin-ui run
      working-directory: ./application/admin-ui
      run: |
        npm install
        yarn build
    
    - name: Write the cypress.env.json file
      working-directory: ./cypress-tests
      run: |
        echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      
    - name: Cypress run
      working-directory: ./cypress-tests
      run: |
        npx cypress run
