name: Node.js CI
on:
  workflow_dispatch:
    inputs:
      amb:
        description: 'Selecionar algum destes ambientes: dev / hlg'
        required: false
        default: 'hlg'
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up server
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run backend nohup
      run: |
        cd application/server 
        npm install
        npm run prisma:generate
        npm run docker:db
        npm run db:init
        nohup npm start &
        
    - name: Run frontend nohup
      run: |
        cd application/admin-ui 
        npm install
        nohup yarn start &
        
    - name: Write the cypress.env.json file
      run: |
        echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
        
    - name: Cypress run
      run: |
       npm i
       npx cypress run --config-file config/${{github.event.inputs.amb || env.DEFAULT_AMB}}.config.js
