name: Node.js CI
on:
  workflow_dispatch:
    inputs:
      amb:
        description: 'Selecionar algum destes ambientes: dev / hlg'
        required: false
        default: 'hlg'
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up server
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run backend nohup
      run: |
        cd application/server 
        npm install
        npm run prisma:generate
        npm run docker:db
        npm run db:init
        nohup npm start &
